### ISSUE TITLE
STM32G070KBT6 / G071KBT6: False chipid reading

### ISSUE THREAD

**Issue by gustavolaureano** [stlink-org/stlink#1017]
- Programmer/board type: [Stlink V2]
- Operating system and version: [Windows 10]
- **Stlink tools version** and/or git commit hash: [v1.6.1-88-g6f36574]
- Stlink commandline tool name: [st-util / st-info]
- Target chip (and board if applicable): [STM32G070KBT6 / STM32G071KBT6]

Commandline-Output:

st-util
2020-08-21T10:51:22 WARN common.c: unknown chip id! 0x5fa0004

st-info --chipid
0x0004

ST-Link Utility correctly identify the chipid for both (STM32G070KBT6 / STM32G071KBT6) micro-controllers:
Device ID:0x460 

But st-util / st-info reports the wrong chipid:
st-info --chipid
0x0004

This problem is happening only with my LQFP32 (STM32G07xKB) chips, both Revision B

I tested with 3 different st-link fw versions: V2J32S7 / V2J36S7 / V2J37S7 (latest)
and all of then presented this same behavior.

I also run the st-info on a Nucleo64 board (G071RB), with the latest ST-Link firmware (V2J37M26)
and a STM32G071RB (rev 2C) target, in this case the chipid was correct:
st-info --chipid
0x0460

COMPLEMENTING:
I also ran the "st-info --chipid" using the same ST-Link v2 (V2J37S7) connected to an STM32L432, and it reported the correct chipid (0x0435)

Is there anything else that I can do to help solving this issue?

Thank you for your support.

The stlink project maintainers

**Comment by gustavolaureano** [comment]
I conducted more tests here and found the issue, the problem was the HW connection in between my ST-Link and my custom board with the G070, the default SWD frequency was too high for it and all read data was corrupted (although it was always reading 0x0004 as chipid).

I recompiled the st-info to open the ST-Link with a lower SWD freq (100KHz) and it read the correct chipid (0x0460)

Maybe it could be a feature request? ability to set the SWD frequency in every cmd tool? (st-info, st-util)
I could implement it later today

**Comment by gustavolaureano** [comment]
Ok, now I am reopening this issue because I just confirmed that my HW connection is not the culprit, I connected a J-Link to my custom board using the same adapter and cable that I use with the ST-Link, and it connected to the target (SWD clock @4MHz , checked with an oscilloscope) and acquired RTT messages for more than a hour without a single problem, so it seems that the problem is somewhere in between the ST-Link V2 (V2J37S7) and the libstlink (v1.6.1-88-g6f36574) when the SWD clock is set above 480KHz, as it still works with 480KHz.

**Comment by Ant-ON** [comment]
This is very similar to reset problems... Could you try https://github.com/Ant-ON/stlink/commits/try_h7_debug ?

**Comment by Nightwalker-87** [comment]
Ping @gustavolaureano

**Comment by Nightwalker-87** [comment]
Ping  @gustavolaureano.

**Comment by gustavolaureano** [comment]
Hi,
ATM I do not have access to the hw with the LQFP32, I should have it in hand again by the middle of next week, as soon as I test it I report here

**Comment by gustavolaureano** [comment]
> @gustavolaureano This is very similar to reset problems... Could you try the develop branch ?

Ok! will try the dev branch

**Comment by gustavolaureano** [comment]
Just built the develop branch on a Windows machine and tested with an STM32G070KB (LQFP32), and the st-info --probe reported the ID correctly, seems to be solved (y)

![2021-05-19 16_45_08-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/25323632/118833850-14610180-b8c2-11eb-982a-0e7868884805.png)

**Comment by Nightwalker-87** [comment]
@gustavolaureano Does it already work with Release **v1.7.0** (Commit: 179650df40295b0af3a148ddfb2c467a0334f54a) ?
@Ant-ON I assume #1126 is the actual fix for this issue. The previous commit ee491d9672dbbe543c1a075d7bc79fc5725bcfd2 may fail. Can you verify this with your hardware @gustavolaureano? This would allow to attach this issue to the actual fix for documentation purposes.

**Comment by gustavolaureano** [comment]
> @gustavolaureano Does it already work with Release **v1.7.0** (Commit: [179650d](https://github.com/stlink-org/stlink/commit/179650df40295b0af3a148ddfb2c467a0334f54a)) ?
> @Ant-ON I assume #1126 is the actual fix for this issue. The previous commit [ee491d9](https://github.com/stlink-org/stlink/commit/ee491d9672dbbe543c1a075d7bc79fc5725bcfd2) may fail. Can you verify this with your hardware @gustavolaureano? This would allow to link this issue to the actual fix for documentation purposes.

Hi @Nightwalker-87 
Just tested it, you are right, v1.7.0 works and commit ee491d9 not:

v1.7.0-dirty:

Found 1 stlink programmers
  version:    V2J36S7
  flash:      131072 (pagesize: 2048)
  sram:       36864
  chipid:     0x0460
  descr:      G070/G071/G081
  
  
v1.6.1-296-gee491d9-dirty:

Found 1 stlink programmers
  version:    V2J36S7
  flash:      0 (pagesize: 0)
  sram:       0
  chipid:     0x0000
  descr:      unknown device

**Comment by Nightwalker-87** [comment]
Fixed by #1126.
