### ISSUE TITLE
STM32F415RGT6: Flash programming error

### ISSUE THREAD

**Issue by UrbanJacobs** [stlink-org/stlink#1043]
Thank you for giving feedback to the stlink project.

**NOTICE: Please read and follow instructions in #906 before submitting a ticket. This feature request will be deleted without notice when not enough information is provided! So please ensure that all fields are filled out.**

- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers and other contributors to isolate and target your respective issue, please take some time to fill out each of the following items appropriate to your specific problem:

- Programmer/board type: [Stlink /v2]
- Operating system and version: [Linux (Debian 10)]
- **Stlink tools version** and/or git commit hash: [v1.6.1]
- Stlink commandline tool name: [st-flash]
- Target chip (and board if applicable): [STM32F415RGT6]

Futher we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline-Output:

```
2020-09-30T18:29:13 ERROR common.c: Verification of flash failed at offset: 6144
stlink_fwrite_flash() == -1
```

Expected/description:

Flash programming is broken: The device can't be flashed multiple times without saying `st-flash erase` prior to each time. The bug was introduced with commit **09ea99ae** ("*Add support for STLink V3*").

Thank you for your support.

The stlink project maintainers

**Comment by Ant-ON** [comment]
Can you try https://github.com/Ant-ON/stlink/tree/flash_loader_rework? I'm trying to improve a work of bootloaders...
