### ISSUE TITLE
Understand the change an executed `cargo flash` introduces in reference to this stlink toolset.

### ISSUE THREAD

**Issue by stappersg** [stlink-org/stlink#1048]
_Originally posted by @Nightwalker-87 in https://github.com/stlink-org/stlink/issues/1007#issuecomment-704571402_

> However it would be helpful to understand the change an executed `cargo flash` introduces in reference to this stlink toolset.

Right now I see no other way to help with this, then creating a fresh issue for it.

**Comment by stappersg** [comment]
In an attempt to add value.

`cargo` is the build tool for _rust_.    (Something like `maven` for _java_)

`cargo flash` uses source code provided by the project  https://probe.rs

The _stlink_ parts of _probe-rs_ are in https://github.com/probe-rs/probe-rs/tree/master/probe-rs/src/probe/stlink

**Comment by stappersg** [comment]
Closing the issue that was opened four months ago by me.  Because I think the project is beter of with this issue being closed.

**Comment by Nightwalker-87** [comment]
Please leave closing of issues to automation and/or administration within this project.

**Comment by Nightwalker-87** [comment]
Failed contribution - Issue has been closed without anything to complete.
