### ISSUE TITLE
st-util v1.6.1 does not recognize option --freq

### ISSUE THREAD

**Issue by joseph-cb** [stlink-org/stlink#1055]
Thank you for giving feedback to the stlink project.

**NOTICE: Please read and follow instructions in #906 before submitting a ticket. This feature request will be deleted without notice when not enough information is provided! So please ensure that all fields are filled out.**

- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers and other contributors to isolate and target your respective issue, please take some time to fill out each of the following items appropriate to your specific problem:

- Programmer/board type: [stlink v2-1] (e.g Stlink /v1, /v2, /v2-clone, /v2-1)
- Operating system and version: [Linux] (e.g Linux, Mac OS X, Windows)
- **Stlink tools version** and/or git commit hash: [baab8ca Updated ISSUE_TEMPLATES] (e.g v1.1.0/git-c722056)
- Stlink commandline tool name: [st-util] (e.g `st-info`, `st-flash`, `st-util`)
- Target chip (and board if applicable): [STM32L452] (e.g STM32F402VG)

Futher we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline-Output:

```
pi@pi-0c:~/ws/stlink/build/Release/bin$ ./st-util --freq=480k
./st-util: unrecognized option '--freq=480k'
st-util
2020-10-21T16:51:33 WARN common.c: unknown chip id! 0x374b
2020-10-21T16:51:33 INFO gdb-server.c: Listening at *:4242...
^C1 pi@pi-0c:~/ws/stlink/build/Release/bin$ ./st-util --version
v1.6.1-1-gbaab8ca-dirty
```

Expected/description:

Tutorial page says that both `st-flash` and `st-util` can take --freq=480k as option in version 1.6.1. I try that option with `st-link` but it did not recognize. `st-flash` can successfully recognized the option.

Thank you for your support.

The stlink project maintainers

**Comment by Nightwalker-87** [comment]
@joseph-cb I think this is simply an error in our tutorial.
The `--freq` argument was added in #893 and is only available for `st-flash`.
So this is not a bug in the toolset. However I'll fix our documentation. Thanks for the hint! :+1:
