### ISSUE TITLE
STM32f103C8: undefined symbol: libusb_set_option

### ISSUE THREAD

**Issue by dcmde** [stlink-org/stlink#1089]
- I made serious effort to avoid creating duplicate or nearly similar issue

- Programmer/board type: [Stlink v2-clone] (e.g Stlink /v1, /v2, /v2-clone, /v2-1)
- Operating system and version: [Linux] (e.g Linux, Mac OS X, Windows)
- **Stlink tools version** and/or git commit hash: [1.6.1-1] (e.g v1.1.0/git-c722056)
- Stlink commandline tool name: [st-info] (e.g `st-info`, `st-flash`, `st-util`)
- Target chip (and board if applicable): [Stm32f103c8] (e.g STM32F402VG)

Commandline-Output:

```
$ st-info --probe
st-info: symbol lookup error: /usr/lib/libstlink.so.1: undefined symbol: libusb_set_option
```

Expected/description:

I installed the package on my Ubuntu 18.04,
```
$ sudo apt install libusb-1.0-0-dev
$ sudo dpkg -i stlink-1.6.1-1_amd64.deb
(Reading database ... 316701 files and directories currently installed.)
Preparing to unpack stlink-1.6.1-1_amd64.deb ...
Unpacking stlink (1.6.1-1) over (1.6.1-1) ...
Setting up stlink (1.6.1-1) ...
```
Then I was able to use all commands st-info, st-flash, ...
But then I got this error all the time when running any command.
```
$ st-info --probe
st-info: symbol lookup error: /usr/lib/libstlink.so.1: undefined symbol: libusb_set_option
```
I think the problem is not due to the stlink because I can see it with `lsusb` and it worked for some times. Something is "broken" with `libstlink.so` I suppose.
I checked on the internet but could not find anything relevant to my problem.
If you have any idea of the cause of the problem, could you please tell me how to proceed?
Thanks in advance.

**Comment by Nightwalker-87** [comment]
@dcmde: As far as I can see the given file path for the library is not correct.
This issue derives from a compilation error that has been fixed in #978.
