### ISSUE TITLE
[feature] STM32WLx5 Support

### ISSUE THREAD

**Issue by super-cow-powers** [stlink-org/stlink#1090]
Currently the WLx5 family are not supported. 
I would like to open a PR to merge WLx5 support based on the work done for the WB family of chips.
The only real issue is that the WL55 and H7 have the same core_id.

- [x] Programmer/board type: all
- [x] Operating system: all
- [x] Stlink tools version and/or git commit hash: develop/git-4bfaab0
- [x] Stlink commandline tool name: st-info`, `st-flash`, `st-util`
- [x] Target chip (and optional board): STM32WLE5

**Comment by wolsty7** [comment]
I have the NUCLEO-WL55JC1 dev board now and am developing an application based on the STM32WL55JC with that arriving in a few weeks so I'm keen to help with testing where I can.

**Comment by Nightwalker-87** [comment]
@super-cow-powers @wolsty7 Can we finally proceed here?

**Comment by Nightwalker-87** [comment]
Please provide the full device-specific parametres as well as the ID of the respective ST reference manual.
This would allow to complete the generated chip file for this device type which currently serves as a template only.

**Comment by wolsty7** [comment]
@Nightwalker-87 
I tested the NUCLEO-WL55JC1 dev board on fe48a98cb1802732edb117fe60cd9b2fa0689145 and it flashed perfectly

**Comment by Nightwalker-87** [comment]
Device specific parametres for the STM32WLEx series were updated in commit e62b9e1f2a1b6dea7e9ccb053c14c2c6ad0b57d7.
