### ISSUE TITLE
Detecting when the ST-Link or Target was disconnected

### ISSUE THREAD

**Issue by gustavolaureano** [stlink-org/stlink#1151]
Hi,

Is there a way to detect, after opening the ST-Link, when the target or the ST-Link was disconnected?

I am coding an application that requires periodic polling of the target's RAM, but also requires to detect when the target or the ST-Link was disconnected (or not yet connected) and reconnect (in hotplug) as soon as it finds the target / stlink again.

During some tests on Linux I could not get any error from stlink_read_mem32() or even stlink_status() when removing the target on the fly.. my solution was to always close and open the stlink when starting the next reading, which works without problems on Linux, but keeps giving me random "denied access" errors on Windows, something related to the libusb.

Thanks!

Gustavo

**Comment by Ant-ON** [comment]
@gustavolaureano, Hi!

I improved the command status check.
You can try:
https://github.com/Ant-ON/stlink/commits/connect_under_reset_rework

**Comment by Nightwalker-87** [comment]
@gustavolaureano Have you had the chance to try in the meanwhile?

**Comment by gustavolaureano** [comment]
> @gustavolaureano Have you had the chance to try in the meanwhile?

Hi, unfortunately not yet, I will return to this project in the coming weeks, then I report back here :)

**Comment by Nightwalker-87** [comment]
ping @gustavolaureano

**Comment by Nightwalker-87** [comment]
@Ant-ON How shall we proceed here? We need somebody to test.

**Comment by Nightwalker-87** [comment]
@slyshykO Do you have any idea on this one?

**Comment by Nightwalker-87** [comment]
@gustavolaureano Any update on this?

**Comment by Nightwalker-87** [comment]
@Ant-ON: Can you contribute your improvements in order to close this issue?

**Comment by Nightwalker-87** [comment]
This issue is now closed due to inactivity.
Please also note that any version prior to `v1.7.0` is unsupported according to our [#Security Policy](https://github.com/stlink-org/stlink/security/policy#security-policy).
Should the problem persist, please retry with the latest version in the `develop` branch.
If this is the case, one should then open a new ticket.
