### ISSUE TITLE
Writing option bytes on STM32 G070/G071/G081

### ISSUE THREAD

**Issue by spark-ict** [stlink-org/stlink#1155]
when i try to make the flash writable again rith rt-flas i get an error, looks like option boot writting is not implemented yet for this chip

- [x] Programmer/board type: STlink V2
- [x] Operating system an version: Linux
- [x] **stlink tools version** 1.7.0
- [x] stlink commandline tool name: st-flash
- [x] Target chip (and board, if applicable): STM32G070/G071/G081

```
command:  sudo ./st-flash --area=option_boot_add write 0xdffbe1aa
```

Commandline output:

```
2021-06-22T16:37:45 INFO common.c: G070/G071/G081: 36 KiB SRAM, 128 KiB flash in at least 2 KiB pages.
2021-06-22T16:37:45 ERROR common.c: Option bytes boot address writing is currently not implemented for connected chip
2021-06-22T16:37:45 ERROR common.c: Flash option write failed!
```

thank you for helping us. if you want us to do further investigation please let me know

best regards,
Guus Hamann
Rural Spark

**Comment by Nightwalker-87** [comment]
Please provide the full device-specific parametres as well as the ID of the respective ST reference manual.
This would allow to complete the existing chip file for this device type.

**Comment by Nightwalker-87** [comment]
The required device-specific parametres according to the related ST reference manual are available in the chip file and have been verified with #1216. However they don't appear to be read due to a missing implementation in `common.c`.

**Comment by Nightwalker-87** [comment]
Indeed, I can confirm, we only have `Write option control register F0`, but no `Write option bytes boot address F0`.
This would need to be implemented by a volunteer.

**Comment by Nightwalker-87** [comment]
@gszy @simplerobot: I looked at the switch-case in `int stlink_write_option_bytes(stlink_t *sl, stm32_addr_t addr, uint8_t *base, uint32_t len)` within `option_bytes.c`
There we find: `case STM32_FLASH_TYPE_G0:` without any `break`, so in this case it should proceed with `case STM32_FLASH_TYPE_G4:` where `stlink_write_option_bytes_gx(sl, addr, base, len)` is called, so it should actually work...

**Comment by Nightwalker-87** [comment]
I've done some further research on this issue:
The only evidence for the observed behaviour is found in option_bytes.c (Line 1078):

```
  switch (sl->flash_type) {
  case STM32_FLASH_TYPE_F7:
    ret = stlink_write_option_bytes_boot_add_f7(sl, option_bytes_boot_add);
    break;
  default:
    ELOG("Option bytes boot address writing is currently not implemented for connected chip\n");
    break;
```

This implies that a wrong `flash_type` must have been defined in the respective chip file `G070/G071/G081` in the particular case (`flash_type = 5` instead of `flash_type = 7`), dependent on the order of the defined `enum stlink_flash_type { }` in `stlink.h`

Commit 8d96e769f32d1c85be913f77e6aab4b1d84b80b1 introduced a human readable form for the parameter `flash_type` to avoid such bugs and/or accidental mistakes.
