### ISSUE TITLE
[feature] Add ability to have multiple GDB clients connected to st-util instance

### ISSUE THREAD

**Issue by c-grant** [stlink-org/stlink#1190]
Recently I was trying to debug a multi executable environment with different IDEs. The current GDB server in st-util will only accept 1 connection at a time, which makes debugging this kind of projects difficult. This is a request to implement multi GDB client connections to the GDB server in st-util

**Comment by Nightwalker-87** [comment]
Closing this feature request due to inactivity and obvious lack of general interest.
