### ISSUE TITLE
[feature] Unlock controller with "st-flash"

### ISSUE THREAD

**Issue by M-Reimer** [stlink-org/stlink#1193]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific request.

- [x] Programmer/board type: [V2-clone] (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)
- [x] Operating system an version: [Linux] (e.g Linux, macOS, Windows)
- [x] **stlink tools version** and/or git commit hash: [1.7.0] (e.g v1.6.1/git-d0416149)
- [x] stlink commandline tool name: [st-flash] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [x] Target chip (and board, if applicable): [STM32F103] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline output:

I got a flash error reported which I can't reproduce, now, as the chip is already unlocked.

Expected/description:

For me this is a long term issue that happens for all kinds of open source "alternative firmware" projects.

Usually controllers are locked in existing devices. To change the firmware it is needed to unlock the controller. At least in my experience the stlink utilities don't come with something to do this and the st-flash utility only reports some useless error which does not point into the right direction (locked flash).

My usual workaround is the following openocd command which just does what is needed here:

`$ openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c "init" -c "halt" -c "stm32f1x unlock 0" -c "shutdown"`

Expected behavior: I would actually prefer if the utility "st-flash" would just unlock the controller if it is locked. After all I clearly told it to write firmware, so I expect it to do every step that is needed for that to succeed.

**Comment by Nightwalker-87** [comment]
Closing this feature request due to inactivity and obvious lack of general interest.
