### ISSUE TITLE
STM32H735: Set Hardware Breakpoints For External Bus

### ISSUE THREAD

**Issue by c-grant** [stlink-org/stlink#1219]
Programmer/board type: [STLINK V3 on STM32H735-DK]
Operating system an version: [Windows 10 19042.1083]
stlink tools version and/or git commit hash: [1.7.0] + pull requests to access external memory
stlink commandline tool name: [st-util]
Target chip (and board, if applicable): [STM32H735 on STM32H735-DK]

GDB is setting breakpoints based on the XML memory map designation of "rom" or "ram", which is hardcoded in st-util for a given processor

However the external bus can be RAM or ROM depending on design. The STM32H735-DK has external FLASH at address 0x90000000. As a result, because the entire external memory range is "ram" as it could be either, software breakpoints (Z0) get sent when a breakpoint is created and the never get tripped as the memory area is read only.

**Comment by Nightwalker-87** [comment]
I agree that it is not very clever to have hardcoded memory maps for devices in `gdb-server.c`.
This should either be part of the device-specific `.chip` files we use or alternatively go into separate device-specific config files which would also allow for individual adjustments.
