### ISSUE TITLE
[feature] Add command line option to skip voltage check

### ISSUE THREAD

**Issue by lucas-camp** [stlink-org/stlink#1264]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific request.

- [x] Programmer/board type: [STLINK/V2-onboard]
- [x] Operating system an version: [Linux]
- [x] **v1.7.0-201-g254a525**
- [x] stlink commandline tool name: [st-flash]
- [x] Target chip (and board, if applicable): [STM32L476RG (NUCLEO-L476RG)]

We have several NUCLEO-L476RG (MB1136 C-04) boards with onboard STLINK/V2-1 (firmware version V2J39M27) programmers. Flashing the L476RG with the attached STLink works flawlessly. We cut off the programmer and connected it as an external programmer. Trying to flash the board yields the following error:
```
2022-08-19T10:23:21 ERROR flashloader.c: Target voltage (6 mV) too low for flash writes!
```

Using the same procedure for a NUCLEO-F411RE (MB1136 C-04) raises a similar error but the flashing is successful, because `st-flash` falls back to 8-bit flash writes.
```
2022-08-19T11:17:02 INFO flashloader.c: Target voltage (6 mV) too low for 32-bit flash, using 8-bit flash writes
```

Looking at the [schematics](https://stm32world.com/images/b/bd/ST-Link_V2.1_Original_Schematics.png) we noticed, that resistor R9 seems to be mandatory for `st-flash` to read the correct voltage. But none of our programmers has this resistor soldered on. Besides the fact we could upgrade all of our programmers with resistor R9, we want to discuss the possibility to add a command line switch to `st-flash` to skip the voltage check when flashing.

**Comment by Nightwalker-87** [comment]
@lucas-camp: The reason for this implementation & behaviour is that the flash Error Correction Code (ECC) algorithm on STM32L4 devices does not permit a single byte write per design. The current implementation in `flashloader.c` takes this into consideration. Hence there is nothing we can do about this.
