### ISSUE TITLE
[stlink-gui] - stlink-gui fails to start due to failure to load UI file - stlink_1.7.0-1_amd64.deb

### ISSUE THREAD

**Issue by PhilSalkie** [stlink-org/stlink#1286]
**Thank you for giving feedback to the stlink project.**

---

**NOTE: In order to offer sufficient and the best possible support, please read /CONTRIBUTING.md and follow the given instructions _before_ submitting a ticket.**

**Bug reports and/or feature requests will be deleted, if they violate our contribution guidelines and if no issue-template is used!** Thank you for your support.

---

- [X] I made serious effort to avoid creating duplicate or nearly similar issue

I found several other bugs which reported the same issue, and were reported fixed.  It's still a problem in the latest release.

- [N/A] Programmer/board type: [enter here] (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)

- [Linux MX-21.1] Operating system an version: [enter here] (e.g Linux, Windows)
- Debian derivative.  Used the stlink_1.7.0-1_amd64.deb from GitHub as you suggested

- [stlink_1.7.0-1_amd64.deb] **stlink tools version** and/or git commit hash: [enter here] (e.g v1.6.1/git-d0416149)

- [stlink-gui] stlink commandline tool name: [enter here] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [N/A] Target chip (and board, if applicable): [enter here] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline output:

Failed to load UI file: stlink-gui.ui

```
OUTPUT/ERROR of the commandline tool(s)
```
GUI doesn't start

Expected/description:

GUI should start

Copying the file "stlink-gui.ui" from /usr/share/st-link to the CWD lets the GUI start up.  This is obviously wrong behavior.

$ cp -p /usr/share/stlink/stlink-gui.ui .
$ stlink-gui
  (GUI starts up)

**Comment by Nightwalker-87** [comment]
Fixed in commit f93adb92f2e4ecf05a9361cb723c98693586929d.
