### ISSUE TITLE
Documentation bug? Installation on a Mac (M1)

### ISSUE THREAD

**Issue by timregan-cri** [stlink-org/stlink#1296]
In the main [README.md](https://github.com/stlink-org/stlink/blob/6bc70f776ab9f52bb9c11c57eeef399e33765850/README.md?plain=1#L87) it says

> MacOS: Users can open a terminal window and then follow the same procedure as for installing on Linux

But [the instructions for installing on Linux](https://github.com/stlink-org/stlink/blob/6bc70f776ab9f52bb9c11c57eeef399e33765850/README.md?plain=1#L72) start

> We recommend to install `stlink-tools` from the package repository of the used distribution

and then lists the linux distributions.

> - Debian Linux: [(Link)](https://github.com/stlink-org/stlink/releases)  
> - Ubuntu Linux: [(Link)](https://github.com/stlink-org/stlink/releases)
> - Arch Linux: [(Link)](https://www.archlinux.org/packages/community/x86_64/stlink)
> - Alpine Linux: [(Link)](https://pkgs.alpinelinux.org/packages?name=stlink)
> - Fedora: [(Link)](https://src.fedoraproject.org/rpms/stlink)
> - Gentoo Linux: [(Link)](https://packages.gentoo.org/packages/dev-embedded/stlink)

None of those look right for the Mac (M1). What is the correct way to install on a Mac, and should that be covered in the installation section of the README?

(N.B. there is a [brew package](https://formulae.brew.sh/formula/stlink), perhaps that is the preferred route?)

**Comment by gszy** [comment]
See 0d96e362696c5b9be0f98ea3187bbfcca12dfd66 where the `README` was updated.

It [seems](https://github.com/Homebrew/homebrew-core/blob/master/Formula/stlink.rb) the Homebrew package follows upstream releases, so I think it should work for you. Note that version 1.7.0 is quite old and does not support for some newer MCUs.
