### ISSUE TITLE
 st-util: symbol lookup error: st-util: undefined symbol: init_chipids

### ISSUE THREAD

**Issue by ayushman22git** [stlink-org/stlink#1297]
**Thank you for giving feedback to the stlink project.**
---
**NOTE: In order to offer sufficient and the best possible support, please read /CONTRIBUTING.md and follow the given instructions _before_ submitting a ticket.**

**Bug reports and/or feature requests will be deleted, if they violate our contribution guidelines and if no issue-template is used!** Thank you for your support.

- [x] I made serious effort to avoid creating duplicate or nearly similar issue
 Have tried the solution mentioned on this link. [https://github.com/stlink-org/stlink/issues/1189] but the solution mentioned doesn't help in my case. Hence wanted to raise an issue - Please forgive if this is not acceptable. I am new to github and linux tools. 
In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific problem.
- [x] Programmer/board type: [STLINK / V2] (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)
- [x] Operating system an version: [Ubuntu 22.04 LTS] (e.g Linux, Windows)
- [x] **stlink tools version** and/or git commit hash: [v1.7.0+ds-1] (e.g v1.6.1/git-d0416149)
- [x] stlink commandline tool name: [st-info] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [x] Target chip (and board, if applicable): [STM32 NUCLEO-F746ZG] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

**Issue 1**

**Commandline output:**
```
ayushman_ubuntu@UbuntuLTS:~$ st-util
st-util: symbol lookup error: st-util: undefined symbol: init_chipids
```
Description: Faced similar issue in [link](https://github.com/stlink-org/stlink/issues/1189)  and hence proceeded as per steps mentioned there. Firstly, stlink doesn't seem to be removed and secondly  reinstallation doesn't work.

**Issue 2**  
```
ayushman_ubuntu@UbuntuLTS:~$ sudo apt remove --purge libstlink1

[sudo] password for ayushman_ubuntu: 

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

The following packages will be REMOVED

  libstlink1* stlink-tools*

0 to upgrade, 0 to newly install, 2 to remove and 14 not to upgrade.

After this operation, 311 kB disk space will be freed.

Do you want to continue? [Y/n] Y

(Reading database ... 341094 files and directories currently installed.)

Removing stlink-tools (1.7.0+ds-1) ...

Removing libstlink1:amd64 (1.7.0+ds-1) ...

Processing triggers for man-db (2.10.2-1) ...

Processing triggers for libc-bin (2.35-0ubuntu3.1) ...

/sbin/ldconfig.real: /lib32/libstlink.so.1 is not a symbolic link



(Reading database ... 341075 files and directories currently installed.)

Purging configuration files for stlink-tools (1.7.0+ds-1) ...

ayushman_ubuntu@UbuntuLTS:~$ sudo apt remove --purge stlink

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

E: Unable to locate package stlink

```
**Description of 2rd issue** -- while libstlink is successfully removed, I get error for removal of stlink.  

**Issue 3**

**Commandline output:** 
```
ayushman_ubuntu@UbuntuLTS:~$ sudo dpkg -i stlink_1.7.0-1_amd64.deb

dpkg: error: cannot access archive 'stlink_1.7.0-1_amd64.deb': No such file or directory

```

**Expected/description:**

In the solution suggested on the [link](https://github.com/stlink-org/stlink/issues/1189), it is suggested to use command sudo dpkg -i stlink_1.7.0-1_amd64.deb to reinstall.  This gives error "No such file or directory". 

**Additional Details that may be needed**
libstlink.so files are present in the location /usr/lib32 . Can refer attached screenshots for more details which were asked in the earlier answer on the topic. 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/121267341/214220089-20249b16-1bdd-4bfd-9f1d-ef30cfe5dd7e.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/121267341/214220137-6a9367cd-f477-4e94-94e6-cea730ae8ab4.png">

**Comment by Nightwalker-87** [comment]
You need to use the current HEAD of the the `develop` branch to include the latest tfixes.
Your version string shows that you used the package from the debian/ubuntu package sources.
We do not maintain these and they are out of date.

**Comment by Nightwalker-87** [comment]
This issue can be traced back to an obviously faulty local installation of the toolset based on package sources.
The Debian Bookworm (Testing) package sources are also the base for the deb-package repo of Ubuntu 22.04 LTS. Thus the deb-packages of the stlink-toolset are identical. Having re-checked the repo-based installation of the related `stlink` packages on Debian (Testing) revealed that there is no compilation-related problem or bug here in the toolset itself.

In order to resolve this problem on the local instance, it is recommended to remove all leftovers from previous installations based on the list of installed files from the package info in the repository.
Afterwards a clean install either by compiling following the official project tutorial or a package install from the repository should succeed without any issues.

Against this background we can safely mark this issue as resolved.
