### ISSUE TITLE
Are chip IDs 482 and 497 known and should be supported?

### ISSUE THREAD

**Issue by victor-dryad** [stlink-org/stlink#1301]
Found 2 stlink programmers
1.
  version:    V3J12S1
  serial:     003000215553500920393256
  flash:      0 (pagesize: 0)
  sram:       0
  chipid:     0x0482
2.
  version:    V3J12S1
  serial:     004C00293331510833323639
  flash:      0 (pagesize: 0)
  sram:       0
  chipid:     0x0497

For example:

$ st-flash --area=optcr1 read
st-flash 1.7.0
2023-04-06T16:52:05 INFO usb.c: Unable to match requested speed 1800 kHz, using 1000 kHz
2023-04-06T16:52:05 WARN common.c: unknown chip id! 0x497
Failed to connect to target

**Comment by Nightwalker-87** [comment]
Two steps to answer your question:
1) You need to make use of the `development` branch.
2) Refer to header stm32.h to check for supported device IDs. --> Yes both are supported.
