### ISSUE TITLE
stm32f411ceu6: stlink clone can only flash once

### ISSUE THREAD

**Issue by noblepepper** [stlink-org/stlink#1308]
**Thank you for giving feedback to the stlink project.**

---

**NOTE: In order to offer sufficient and the best possible support, please read /CONTRIBUTING.md and follow the given instructions _before_ submitting a ticket.**

**Bug reports and/or feature requests will be deleted, if they violate our contribution guidelines and if no issue-template is used!** Thank you for your support.

---

- [ ] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific problem.

- [ ] Programmer/board type: V2-clone
- [ ] Operating system an version: Linux Debian 10.13
- [ ] **stlink tools version** and/or git commit hash: commit e8c6d98ca52745d55b9ce1f5b15d72fc0dcd4289 (HEAD -> nightly, origin/nightly, origin/f2023_2)
- [ ] stlink commandline tool name: st-flash
- [ ] Target chip (and board, if applicable):  STM32F411xC_xE from st-info, cheap black pill stm32f411ceus clone

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Flashing with stlink clone works the first time, fails the second time, flashing with stm nucleo64 onboard stlink succeeds but program doesn't run until target is reset, flashing stm nucleo64 onboard stlink again succeeds and program runs without target reset.

Commandline 
main.bin is simple program to blink led
nohup st-flash --debug write main.bin 0x8000000 >clone_first_run.log
Led blinks
nohup st-flash --debug write main.bin 0x8000000 >clone_second_run.log
Led does not blink, after reset led is off
nohup st-flash --debug write main.bin 0x8000000 >stlink_first_run.log
Led is on, blinks after target is reset
nohup st-flash --debug write main.bin 0x8000000 >stlink_second_run.log
Led blinks

Expected/description:

Led blinks after flashing with clone
[clone_first_run.log](https://github.com/stlink-org/stlink/files/11301898/clone_first_run.log)
[clone_second_run.log](https://github.com/stlink-org/stlink/files/11301900/clone_second_run.log)
[stlink_first_run.log](https://github.com/stlink-org/stlink/files/11301901/stlink_first_run.log)
[stlink_second_run.log](https://github.com/stlink-org/stlink/files/11301902/stlink_second_run.log)

**Comment by Nightwalker-87** [comment]
@noblepepper I don't see a bug here. The observed behaviour may be one of those risks when using st-link clone programmers. If one can not verify that the assembled chip is an original part, everything can happen...
Please use original hardware or at least make sure that your cloned device has a original chip manufactured by ST-Microelectronics by replacing the chip itself.
