### ISSUE TITLE
STM32MP151C: How to connect to second core? (Cortex M4F)

### ISSUE THREAD

**Issue by Olangu** [stlink-org/stlink#1316]
- [ X ] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific problem.

- [ ST-LINK/V2-1 (NUCLEO-G070RB) ] Programmer/board type: [enter here] (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)
- [ Linux ] Operating system an version: [enter here] (e.g Linux, Windows)
- [ v1.6.1 ] **stlink tools version** and/or git commit hash: [enter here] (e.g v1.6.1/git-d0416149)
- [ st-util ] stlink commandline tool name: [enter here] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [ STM32MP151C ] Target chip (and board, if applicable): [enter here] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline output:

```
2023-06-23T09:33:17 WARN common.c: Invalid flash type, please check device declaration
2023-06-23T09:33:17 ERROR gdb-server.c: Unsupported Target (Chip ID is 0000000000, Core ID is 0x6ba02477).
```

Expected/description:

I expect to be able to connect to second core (which is in engineering mode).

With ST-LINK_gdbserver I need to specify "-m 2"

**Comment by Nightwalker-87** [comment]
This device is incompatible and not supported by this toolset.
Also support for v1.6.1 of the toolset has ended (see /SECURITY.md)
