### ISSUE TITLE
Bug report 1322 locked

### ISSUE THREAD

**Issue by karstengit** [stlink-org/stlink#1323]
**Please foirgive this bug report**, but it is not possible to continue any collection of information in https://github.com/stlink-org/stlink/issues/1322
It is O.K. when the developers don't want to support such a case and close the bug.
But it is not understandable why this issue has been **locked**, so that other affected users are able to change informations within this case regarding this tool. This is the intention of this bug report.

@Nightwalker-87 Thanks for the hint of the tutorial that can be found at /doc/tutorial.md !
The tutorial explains how bad this clone chips are, but offer no solution when they are already on your tinker table.
The modded version st-flash 1.6.0-31-gf5d0454-dirty in the linked bug shows that this tool can be used without problems for this cloned chips, when the Id's are added.

There are some good links and explanations of the mechanism of chip identification, but no hint how to add an unknown id or how to debug if the verify after flash has failed?

Some public  analyze of the code. In common.c can be found:

```
int32_t stlink_load_device_params(stlink_t *sl) {
  // This seems to normally work so is unnecessary info for a normal user.
  // Demoted to debug. -- REW
  DLOG("Loading device parameters....\n");
  const struct stlink_chipid_params *params = NULL;
  stlink_core_id(sl);
  uint32_t flash_size;

  if (stlink_chip_id(sl, &sl->chip_id)) {
    return (-1);
  }

  params = stlink_chipid_get_params(sl->chip_id);

  if (params == NULL) {
    WLOG("unknown chip id! %#x\n", sl->chip_id);
    return (-1);
  }
```

This is using

```
// stlink_chip_id() is called by stlink_load_device_params()
// do not call this procedure directly.
int32_t stlink_chip_id(stlink_t *sl, uint32_t *chip_id) {
  int32_t ret;
    ...
    ret = stlink_read_debug32(sl, 0xE0044000, chip_id);
    ...
    ret = stlink_read_debug32(sl, 0xE0042000, chip_id);
  }
```

The idcodes are defined in inc/stm32.h

```
/* STM32 Cortex-M core ids (CPUTAPID) */
enum stm32_core_id {
    ...
    STM32_CORE_ID_M3_r1p1_SWD   = 0x1ba01477,   // (RM0008 Section 31.8.3) F1 SW-DP
```

and used in /stlink-lib/flash_loader.c

```
int32_t stlink_flash_loader_write_to_sram(stlink_t *sl, stm32_addr_t* addr, uint32_t* size) {
    const uint8_t* loader_code;
    uint32_t loader_size;

    if (sl->chip_id == STM32_CHIPID_L1_MD ||
    ...
    } else if (sl->core_id == STM32_CORE_ID_M3_r1p1_SWD ||
```

Now it seems clear how to add the missing idcode.

In chipid.c can be found

```
void dump_a_chip(struct stlink_chipid_params *dev) {
  DLOG("# Device Type: %s\n", dev->dev_type);
  DLOG("# Reference Manual: RM%s\n", dev->ref_manual_id);
  DLOG("#\n");
  DLOG("chip_id 0x%x\n", dev->chip_id);
  DLOG("flash_type %d\n", dev->flash_type);
  DLOG("flash_size_reg 0x%x\n", dev->flash_size_reg);
  DLOG("flash_pagesize 0x%x\n", dev->flash_pagesize);
  DLOG("sram_size 0x%x\n", dev->sram_size);
  DLOG("bootrom_base 0x%x\n", dev->bootrom_base);
  DLOG("bootrom_size 0x%x\n", dev->bootrom_size);
  DLOG("option_base 0x%x\n", dev->option_base);
  DLOG("option_size 0x%x\n", dev->option_size);
  DLOG("flags %d\n\n", dev->flags);
}

struct stlink_chipid_params *stlink_chipid_get_params(uint32_t chip_id) {
  struct stlink_chipid_params *params = NULL;
  for (params = devicelist; params != NULL; params = params->next)
    if (params->chip_id == chip_id) {
      DLOG("detected chip_id parameters\n\n");
      dump_a_chip(params);
      break;
    }

  return (params);
}
```

The base is probably config/chips/F1xx_MD.chip

```
# Chip-ID file for STM32F1xx medium density device
#
dev_type STM32F1xx_MD
ref_manual_id 0008
chip_id 0x410                // STM32_CHIPID_F1_MD
flash_type F0_F1_F3
flash_size_reg 0x1ffff7e0
flash_pagesize 0x400         // 1 KB
sram_size 0x5000             // 20 KB
bootrom_base 0x1ffff000
bootrom_size 0x800           // 2 KB
option_base 0x1ffff800       // STM32_F0_OPTION_BYTES_BASE
option_size 0x10             // 16 B
flags swo
```

Will this team be so graceful to add this to the code, when the needed modifications are tested and published here?

It remains the question how to debug the failed verify, after flashing of the chip in the existing dirty version.

**Comment by Nightwalker-87** [comment]
@karstengit

It is common practise to lock resolved issues in this project - this has nothing to do with this specific issue.

As mentioned before, it is not only that we do not want to provide any support here, but rather that we KNOW from the implementation on how devices are detected and verified that any changes and attempts previously made do break detection of other devices which we don't want. This roots back to the technical design and documentation of the manufacturer and is not a specific problem of this toolset. There is no simple solution to this, especially not by adding further chipid files. The detection routine is the relevant aspect here and this was as far as it is known not designed by anyone within this project.

Against this background and at least to previous attempts on addressing this issue in the history in this project, there should not be any further approaches to mislead users here (may they be in good faith or not). instead I'd recommend to maybe look at other tools for specific intentions on these cloned devices or try to tinker around with it outside of this project. In short: I neither want to see nor deal with this topic any longer in this project.

Thank you for you understanding. :-)
