### ISSUE TITLE
[feature] Provide access to the UART via virtual com port

### ISSUE THREAD

**Issue by srobertjames** [stlink-org/stlink#1334]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific request.

- [x] Programmer/board type: [V2-1] (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)
- [x] Operating system an version: [Linux Ubuntu] (e.g Linux, Windows)
- [x] **stlink tools version** and/or git commit hash: [v1.7.0] (e.g v1.6.1/git-d0416149)
- [x] stlink commandline tool name: [st-util] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [x] Target chip (and board, if applicable): [STM32F446RE NUCLEO-F446] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Is it possible to use st-link to access the virtual COM (serial) port provided by STLink? If so, how do I do that? I do not see any `/dev/ttyS` being created by st-util, and `tio` is not able to find it either.

**Comment by Nightwalker-87** [comment]
No, this is currently not possible.

**Comment by srobertjames** [comment]
I see.  What would be involved in implementing this? I may be able to help, but can find no docs on the ST-Link virtual com port implementation.

**Comment by Nightwalker-87** [comment]
Well, one would need to deep dive into the toolset library codebase and find out how an implementation could look like while maintaining current functionality of this toolset. The other side of the coin is what you mentioned above, should it be publicly available. I'm afraid to say, that I can't provide any help on this topic.

**Comment by Nightwalker-87** [comment]
@srobertjames I found [this link](https://electronics.stackexchange.com/questions/288187/is-it-possible-to-get-st-links-virtual-com-port-working-without-launching-any-p) that may help. As far as I can see, there is no need for any specific implementation.

**Comment by neithernut** [comment]
My personal two cents:

...so they tell you to uninstall modemmanager, which is almost always a good idea. But depending on your distro you won't have that problem anyway.
Imo, the more relevant hint hidden in that stackexcahnge was the fact that you need the USB ACM driver.

**Comment by Nightwalker-87** [comment]
@neithernut Have you been able to test the latter? Does this likely provide a solution from your point of view?

**Comment by neithernut** [comment]
> @neithernut Have you been able to test the latter? Does this likely provide a solution from your point of view?

I've confirmed that, if I plug in my (dated) STM32F411 nucleo board, the device does show up (according to `dmesg`) with the USB ACM driver. I planned playing around with it a bit on the weekend. When I do, I'll report back here, maybe with proposed changes to documentation.

**Comment by neithernut** [comment]
Update: got to play around with my board, and everything works just fine. The device pops up as `/dev/ttyACM0` on my machine and at least 9600 8N1 communication works both ways (I used `minicom` and a simple toy example on the nucleo board).

But now I struggle a bit with where to put this information. Serial communication doesn't concern any of the tools provided in this repo. Maybe we could add some hints to `doc/tutorial.md`? Maybe a new file in `doc/`? Will users even look there?

**Comment by Nightwalker-87** [comment]
@neithernut Thanks for the update. I'll think about how to deal with the documentation-related part soon.

**Comment by Nightwalker-87** [comment]
@neithernut We can add a new section to our `tutorial.md` under "Solutions to common problems" and extend the title to "How-To's & Solutions to common problems" or anything alike.

**Comment by Nightwalker-87** [comment]
I've added a description to our project tutorial in order to resolve this issue which is now closed.
