### ISSUE TITLE
stlink V3 mini not "usable" [Win7 64bit]

### ISSUE THREAD

**Issue by patzf** [stlink-org/stlink#1350]
Hi! As far as I can see, I cannot reply to an already locked discussion, but I have some follow up (see reference to original discussion at the end)

This time it is Windows 7 instead of Windows 10, there were no USB devices attached on the PC before and I copied the binaries of the current stlink release to that PC and pluged in an stlink V3 mini. Upon trying to use the stlink, I get the error message:

st-flash 1.7.0
libusb: info [winusb_get_device_list] The following device has no driver: 'USB\VID_0483&PID_3754&MI_00\7&23F3714E&0&0000'
libusb: info [winusb_get_device_list] libusb will not be able to access it
libusb: info [winusb_get_device_list] The following device has no driver: 'USB\VID_0483&PID_3754&MI_01\7&23F3714E&0&0001'
libusb: info [winusb_get_device_list] libusb will not be able to access it
2023-11-03T19:29:44 WARN usb.c: Couldn't find any ST-Link devices
libusb: warning [libusb_exit] some libusb_devices were leaked

Which kind of driver is stlink missing if everything is brought by the binary release?

**EDIT on 05/11/2023: I tried to build the development branch using cmake / MSVS as described in the compile readme but I get lots of errors during build with MSVS.**

**Anyway:  In the readme I found the following:**

"**NOTE 2:**[ST-LINK drivers](https://www.st.com/en/development-tools/stsw-link009.html) are required for `stlink` to work.

**I am confused now: So the ST-Link driver ARE necessary for the tools to work?**

_Originally posted by @patzf in https://github.com/stlink-org/stlink/discussions/1347_

**Comment by Nightwalker-87** [comment]
Closed by #1347.
