### ISSUE TITLE
stlink-gui: failed to allocate 139988352155568 bytes

### ISSUE THREAD

**Issue by rcubee** [stlink-org/stlink#1356]
- [x] made serious effort to avoid creating duplicate or nearly similar issue
- [x] Operating system and version: linux 6.1.38
- [x] **stlink tools version** and/or git commit hash: v1.7.0-316-g31c7fc6-dirty
- [x] stlink commandline tool name: stlink-gui

Commandline output:
```
$ ./stlink-gui 

(stlink-gui:25286): GLib-ERROR **: 10:38:03.866: ../glib-2.78.1/glib/gmem.c:136: failed to allocate 139988352155568 bytes
Trace/breakpoint trap
```
The program crashes after opening a file.

Commit 33430783b3b18ab88ff89d10d7a2a24dadae2472 seems to be the villain.  Why `g_malloc(<pointer_casted_to_gsize>)` instead of the previous `g_malloc(g_file_info_get_size(file_info))`?

 Changing line 311 from `gui->file_mem.size   = (gsize) file_info;` to `gui->file_mem.size = file_size;` fixed the issue and I was able to flash the device.

**Comment by Nightwalker-87** [comment]
@rcubee That's a good question, I need to check.
