### ISSUE TITLE
Update on #1357

### ISSUE THREAD

**Issue by OSHW-Rico** [stlink-org/stlink#1367]
Just want to give a heads up regarding #1357. It did take me some time to try and use it one the raspberry again, but I can confirm the latest build does indeed work as expected!

The only issue which people may need to be aware of is that the V3MINIE does handle the startup procedure differently than other V2/V3s. When using a STM32 where the BOOT0 Pin is the same as the SWCLK pin. I don't remember which way around it is but the SWCLK has the wrong level on boot-up which leads to the micro controller not running when a debugger is attached and no debug session is active. This does only happen with the V3MINIE, not with V3MINI,V2,V3 or BMP (Black Magic Probe). Just wanted to leave this here, maybe there is a place in the docs to attach this information.

**Comment by Nightwalker-87** [comment]
@OSHW-Rico Thanks for the feedback. We may then close this issue as resolved.
I may consider a note in the docs, if we can reproduce this with another device. :wink:
