### ISSUE TITLE
[feature] Read/write operations on external SPI Serial Flash Memory

### ISSUE THREAD

**Issue by mrkkrn** [stlink-org/stlink#1368]
Does stlink have support for read/write operations over external SPI memory? From docs/source isn't visible at first moment, I assume not.

STM32CubeProgrammer feature to program external flash with support of "external loaders", link for [ST External Loader repo](https://github.com/STMicroelectronics/stm32-external-loader). 

I would like to use write/read operations over SPI memory, external loader from link above looks like good way how to handle it, questions is how to achieve such functionality with stlink. 

Pseudo work-flow should be:
1. Load "external_loader.bin" into Target SRAM
2. Copy data to SRAM at SRAM_ADDR + sizeof(external_loader.bin)
3. Call external_loader.bin->Init to initialize Target 
4. Call external_loader.bin-> (Mass_Ease | Write | Read)

I would appreciate this functionality and I don't hesitate to support it, please do you have any recommendations or tips?

**Comment by Nightwalker-87** [comment]
As to my knowledge such a functionality is currently not available in the toolset.

**Comment by Nightwalker-87** [comment]
Closed due to inactivity and missing interest.
