### ISSUE TITLE
Cmake minimal version mismatch

### ISSUE THREAD

**Issue by Vascom** [stlink-org/stlink#1375]
Cmake policy change CMP0153 from [@6a67](https://github.com/stlink-org/stlink/commit/6a6718b3342b6c5e282a4e33325b9f97908a0692) introduced only in cmake 3.28.
But current minimal required version 3.10.2
```
cmake_minimum_required(VERSION 3.10.2)
```
Also many linux distributions still use version < 3.28. So new versions of stlink can't be build for them.
Need to solve this mismatch.

**Comment by Nightwalker-87** [comment]
Duplicate of #1374.
