### ISSUE TITLE
CH32F103C8T6: Flashing fails because of timeout

### ISSUE THREAD

**Issue by mressl-itba** [stlink-org/stlink#1382]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue
- [x] stlink tools version v1.8 (and earlier)
- [x] Target chip: CH32F103C8T6 (WCH)

Flashing with `st-flash` does not work with the CH32F103C8T6 (Semiconductor company: WCH).

This happens because programming the CH32F103C8T6 is much slower than the original STM32F103, therefore `st-flash` signals a failure as the default timeout value (500 ms, in `flash_loader.c`, line 378) is too low.

I increased the timeout to 10000 ms (less didn't work always), recompiled the code and made a video so you can see for yourselves:

https://github.com/stlink-org/stlink/assets/42745652/b9f3cc23-e285-4a74-bcdf-72a34eba338e

You can find the same issue in a different GitHub project here: https://github.com/blackmagic-debug/blackmagic/issues/990

Some proposals for fixing the problem:
* Increase the default timeout value to 10000 ms.
* Add a command line option to set the timeout value.
* Detect WCH chips and set the timeout value based on this detection (ideas for detection are discussed here: https://www.blaatschaap.be/identifying-32f103-clones/).

I hope this helps many users.

**Comment by Nightwalker-87** [comment]
As stated several times before, there is no official support or maintenance for non-STM32 chips by this toolset.
Thus this ticket will be closed without further explanations.
