### ISSUE TITLE
[STM32L471RG]:  STLINKV3 : can't flash the device. Programmer not supported ?

### ISSUE THREAD

**Issue by Sazerac4** [stlink-org/stlink#1388]
- [X] Programmer/board type: STLINK/V3  (STLINK-V3PWR)
- [X] Operating system an version: [Ubuntu 22.04.4 LTS]
- [X] **stlink tools version** : [v1.8.0] installed from release artifact : `stlink_1.8.0-1_amd64.deb`
- [X]  Command: `st-flash --reset --format=ihex write ./program.hex `
- [X] Target chip : `STM32L471RGT6`

I can't flash the microcontroller. It works with my stlink-v2.

Command line output:
```
st-flash 1.8.0
libusb: error [submit_bulk_transfer] submiturb failed, errno=2
2024-04-22T17:35:50 ERROR usb.c: GET_VERSION send request failed: LIBUSB_ERROR_IO
libusb: error [submit_bulk_transfer] submiturb failed, errno=2
2024-04-22T17:35:50 ERROR usb.c: GET_CURRENT_MODE send request failed: LIBUSB_ERROR_IO
libusb: error [submit_bulk_transfer] submiturb failed, errno=2
2024-04-22T17:35:50 ERROR usb.c: GET_CURRENT_MODE send request failed: LIBUSB_ERROR_IO
libusb: error [submit_bulk_transfer] submiturb failed, errno=2
2024-04-22T17:35:50 ERROR usb.c: ENTER_SWD send request failed: LIBUSB_ERROR_IO
Failed to enter SWD mode
Failed to connect to target
Failed to parse flash type or unrecognized flash type
libusb: error [submit_bulk_transfer] submiturb failed, errno=2
2024-04-22T17:35:50 ERROR usb.c: DEBUG_EXIT send request failed: LIBUSB_ERROR_IO
```

Notes:

- I have modified my udev rules, it is seem the product id was not present. The programmer is not supported ? The new entry added:
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="3757", \
    MODE:="0666", \
    SYMLINK+="stlinkv3_%n"
```

- Library libusb (`dpkg -l libusb-1.0*`)

```
ii  libusb-1.0-0:amd64     2:1.0.25-1ubuntu2 amd64
```

Expected/description:

Uploading the firmware is done without any problems

**Comment by Nightwalker-87** [comment]
@florrant Thanks for putting this up. As to my knowledge this model is not yet supported by this toolset.
Could you make it work based on the changes above? If so, please submit a PR to the `testing` branch.

**Comment by Sazerac4** [comment]
Sorry for the misunderstanding. 
Adding the udev rules wasn't enough to get the device working.
I also tried on a Debian 12 without success (same error message).

Edit:
Debugging with openocd/st-link work well with this programmer
