### ISSUE TITLE
st-util is very slow when stepping through code

### ISSUE THREAD

**Issue by AJ528** [stlink-org/stlink#1391]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue
- [x] Programmer/board type: STLINK V3
- [x] Operating system and version: Linux Mint 21.3
- [x] **stlink tools version** and/or git commit hash: v1.8.0
- [x] stlink commandline tool name: st-util
- [x] Target chip (and board, if applicable): STM32WL55 (NUCLEO-WL55JC1)

I am using st-util as a GDB server to remote debug my STM32 Nucleo board. I have 2 versions of st-util. One I downloaded from the package manager via `sudo apt get install stlink` and the other I compiled from source. Both are version 1.8.0.

When I use the package manager version of st-util to debug code, it takes a fairly long time to single-step through code. Somewhere on the order of 7-10 seconds per step.

I downloaded the source code, compiled it using `make release`, and ran the st-util command from the Release folder. When using that version, I can step through the code much quicker, something like 1-2 seconds per step.

Both versions of st-util report v1.8.0, but I did notice that the compiled version was looking for chipids in `/usr/local/share/stlink/config/chips` whereas the package manager version had put them in `/usr/local/share/stlink/chips`. So apparently there is at least 1 difference between the two versions.

I would expect both versions of the st-util to act identically and be able to step through the code quickly. I almost gave up on st-util because 7-10 seconds per step is way too long.

I experienced this error while testing the code from https://github.com/AJ528/stm32wl_project_template but I doubt the code being debugged actually matters.

Note: this could be related to issue #658

**Comment by Nightwalker-87** [comment]
We have no influence on the package configuration downstream including repacking in the distro repository.
Thus there indeed may be changes, as described, between different distros and to this projects repo.

**Comment by Nightwalker-87** [comment]
In this context I recommend to use the release-version distributed by this project.
