### ISSUE TITLE
v1.8.0 is very slow stepping through code

### ISSUE THREAD

**Issue by AJ528** [stlink-org/stlink#1394]
- [x] I made serious effort to avoid creating duplicate or nearly similar issue
- [x] Programmer/board type: STLINK V3
- [x] Operating system and version: Linux Mint 21.3
- [x] stlink tools version and/or git commit hash: v1.8.0
- [x] stlink commandline tool name: st-util
- [x] Target chip (and board, if applicable): STM32WL55 (NUCLEO-WL55JC1)

I previously reported bug#1391, which was closed because the issue appeared to come from package-manager version of stlink. After doing more research, I can now give a better bug report. 

I installed release version 1.8.0 using the .deb package on the github release page. It installs correctly, but the st-util program takes 7-10 seconds for each step you do in `gdb-multiarch`. However, this problem is solved if you use the latest version of the code on the `testing` branch. It appears that commit feb7eb1 solves the problem.

I don't know if anyone else ran into this problem. It looks like the fix will come out in v1.9.0, but if anyone else runs into this I would suggest either manually adding the line of code in `gdb-server.c` or just compile the latest source code and run off that until v1.9.0.

Note: I would have added this as a follow-up to the previous issue, but since that has been closed I cannot comment on it

**Comment by Nightwalker-87** [comment]
Closed by #1387.
