### ISSUE TITLE
[doc] STM32H573 reports chipid 0x000

### ISSUE THREAD

**Issue by moritz-geier** [stlink-org/stlink#1398]
Hello, 

I'm trying to flash a STM32H573 board with your tools, but the flashing reports always, couldn't connect to device, wether i use `--connect-under-reset` or not. Thus i tried to to use `st-info --probe` to debug the problem, but the program returns this output:
```
Found 1 stlink programmers
  version:    V3J15
  serial:     001E002F3431511631343632
  flash:      0 (pagesize: 0)
  sram:       0
  chipid:     0x000
  dev-type:   unknown
```
The controller sits on a custom board, but STM32CubeIDE is able to flash it, I also tried it on a different version of the board with the same result. On this board there is also a G030 trying to probe it is successful. Is this controller currently not supported? even though on your wiki its stated that all H5 controllers are supported.

**Comment by Nightwalker-87** [comment]
Thanks for the note. I've corrected the list of supported devices which falsely suggested that there is official and full support for Cortex M33 based devices. Support may gradually improve over time however depending on external contributors.
I recommend to stay with the official ST Microelectronics tools for this newer generation of more complex devices for now.
