### ISSUE TITLE
[st-trace] Bug in function static bool read_trace( )

### ISSUE THREAD

**Issue by MikuChan03** [stlink-org/stlink#1400]
Hello Senpai! 🎶🎶🎶

Watashi was innocently enjoying youw sugoi stlink pwogwam, when it hit watashi like a ton of bwicks...
st-twace doesn't actually wowk, like at all &nbsp;&nbsp;(つ﹏<。)

So it dawned on watashi that an ewwow had gotton into this stweamylined, kawaii implementation.
Hewe it is:

```c
static bool read_trace(stlink_t *stlink, st_trace_t *trace) {
  uint8_t* buffer = 0;
  int32_t length = stlink_trace_read(stlink, buffer, sizeof(buffer));
```

The buffew is only 4-8 bytes big, much to small fowthe twace message. Bettew yet, it stands to weason that addwess 0 is not typically mapped into pwogwam memowy, it's kinda special that way 💕.

Doing this, howevew:
```c
static bool read_trace(stlink_t *stlink, st_trace_t *trace) {
  uint8_t buffer[STLINK_V3_TRACE_BUF_LEN];
  int32_t length = stlink_trace_read(stlink, buffer, sizeof(buffer));
```
evewything is hunky-dowy! Weal peachy-cweamy 💯⭐✓

That's all watashi wanted to say.
Sayonawa XOXO

**Comment by Ant-ON** [comment]
@MikuChan03 yes, it's look like big bug in the `read_trace` function implementation
