### ISSUE TITLE
[feature] Prevent installing of hardcoded modprobe config and udev rules

### ISSUE THREAD

**Issue by sansyse** [stlink-org/stlink#1430]
When working with isolated build environments (docker container or local user builds) under Linux it is not usable if the cmake build forces an installation to install files to hardcoded /etc/{modprobe.d,udev} locations. A option like "PREVENT_HARDCODED_INSTALL" would be desirable.

e.g.:
make -j1 CMAKEFLAGS="-DPREVENT_HARDCODED_INSTALL=1" release install

See PR #1431

**Comment by Nightwalker-87** [comment]
Rejected in #1431.
