### ISSUE TITLE
[feature] Integrate ST-LINK Firmware Upgrade Tool

### ISSUE THREAD

**Issue by jsnowy** [stlink-org/stlink#1443]
Is there an official open-source  STLINK firmware upgrader ? Because STSW-LINK007 is not open source and does not have a command-line tool, which is inconvenient. Could ST consider opening up the firmware upgrade SDK so that it can be integrated into this project?

**Comment by Nightwalker-87** [comment]
No, there isn't and there will be no attempts within this project regarding this topic.
The firmware including all released versions is proprietary and thus not published by ST Microelectronics. It is solely distributed through software licensed by the manufacturer (bundled) and there appears to be no intention to change this practise either.
