### ISSUE TITLE
Mingw build problem

### ISSUE THREAD

**Issue by ivictbor** [stlink-org/stlink#169]
Hi guys! Thank for your job! I successfully used your project on linux ubuntu and arch linux, but now I want to use it on windows. I installed latest mingw, cloned the repo and executed:

``` bash
./autogen.sh
./configure
```

But configure crashes with:

```
./configure: line 4357: syntax error near unexpected token `USB,'
./configure: line 4357: `PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0.0,,'
```

What I do wrong? Do I need to install libusb to mingw? Where can I find it? Is there some manual for compiling texane/stlink on windows? You have alredy done a great job, and it should be some approximate instruction for compiling on windows or pre-compiled binarys.
I also tried:
- Download and extract two archive with pkg-config and glib to my mingw folder (from this post: http://mingw-users.1079350.n2.nabble.com/Install-pkg-config-tp5181785p5181863.html)
- Download and extract libusb-win32-bin-1.2.6.0/lib/gcc/libusb.a to mingw/lib/ 
  But the problem remains.

Thanks in advance

**Comment by franzbischoff** [comment]
Installed libusb as above, but the problem persists...

./configure: line 4364: syntax error near unexpected token `USB,'
./configure: line 4364: `PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0.0,,'

Where does stlink look for libusb?
