### ISSUE TITLE
[feature] Support for ITM trace port (printf style debugging)

### ISSUE THREAD

**Issue by Slamy** [stlink-org/stlink#179]
This project is great but there is still no possibilty to acccess the ITM trace port under linux. Is this planned? I could only find st-term which tries to handle this in a different way.
I'm trying to hack this myself into your code but I don't know where to start as I couldn't find a lot of the needed magic numbers inside the debug documtentation of the stm32f4.

**Comment by xor-gate** [comment]
Duplicate of #136
