### ISSUE TITLE
st-util cannot load my chip parameters, either can *.elf file be loaded, why and how to solve it ?

### ISSUE THREAD

**Issue by gitsocket** [stlink-org/stlink#194]
I use stm32f103vet6 with 512K flash and 64K ram. When I start st-util, it showed that:

STM32F1-workarea/Project/GPIO-example$ sudo st-util  
libusb_handle_events() timeout
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
2013-12-07T02:10:23 INFO src/stlink-common.c: Loading device parameters....
libusb_handle_events() timeout
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
2013-12-07T02:10:26 WARN src/stlink-common.c: unknown chip id! 0
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
Chip ID is 00000000, Core ID is  00000000.
libusb_submit_transfer(-6)
[!] send_recv
Listening at *:4242...

And in arm-none-eabi-gdb 's view :

(gdb) target remote localhost:4242
Remote debugging using localhost:4242
0x00007f78 in ?? ()
(gdb) load main.elf
Loading section .isr_vector, size 0x1d0 lma 0x8000000
Load failed

I'm sure I have set the board set from SRAM so that it can be reprogramed, and I alse tried keeping reset the board. I have no idea about that... Why and how to solve the problem?

**Comment by Nightwalker-87** [comment]
It would clearly be helpful to find out the reason for the observed behaviour.

**Comment by Nightwalker-87** [comment]
The described behaviour is related to the external `libusb` library preventing communication to the device.
This issue should be fixed since #374.
