### ISSUE TITLE
[feature] OTP Area Programming

### ISSUE THREAD

**Issue by ababodpx** [stlink-org/stlink#202]
Why it isn't possible program the OTP area in STM32Fxx, using st-flash???

**Comment by xor-gate** [comment]
It is not possible because it is not implemented currently (at time of writing).

**Comment by Nightwalker-87** [comment]
Who can contribute here?

**Comment by Nightwalker-87** [comment]
@Ant-ON Would it be difficult to implement this? What do you think about it?

**Comment by Nightwalker-87** [comment]
Closed due to inactivity and missing interest.
