### ISSUE TITLE
STM32F4-Discovery: Can't read the board

### ISSUE THREAD

**Issue by ScottChaung** [stlink-org/stlink#233]
The tool st-util can't read the board after I download a program to it. 
The infomation showed:

libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
2014-05-12T11:24:17 INFO src/stlink-common.c: Loading device parameters....
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
2014-05-12T11:24:17 WARN src/stlink-common.c: unknown chip id! 0
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
Chip ID is 00000000, Core ID is  00000000.
libusb_submit_transfer(-1)
[!] send_recv
Listening at *:4242...
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_recv
libusb_submit_transfer(-1)
[!] send_only

Is this a bug?

**Comment by xor-gate** [comment]
Closing this old issue, please test against the stlink tools from master, and latest stlink firmware. Open a new issue when this problem still exists.

**Comment by Nightwalker-87** [comment]
Should be properly verified as well to be sure.

**Comment by Nightwalker-87** [comment]
@ScottChaung: I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0? Please verify.

**Comment by Nightwalker-87** [comment]
Does this still occur on the `v1.3.0-patch` branch?

**Comment by Nightwalker-87** [comment]
According to the `libusb` documentation (https://vovkos.github.io/doxyrest/samples/libusb/enum_libusb_error.html) this issue denotes an I/O error. As the physical connection is interrupted, this is a hardware error and thus not related to the `stlink` toolset.
I such a case the quality of the connection (cables, connectors and solder joints) should be verified and fixed if necessary.

Against this background we can finally close this issue as resolved.
