### ISSUE TITLE
st-util segfaults when printing array in gdb

### ISSUE THREAD

**Issue by dflogeras** [stlink-org/stlink#256]
I have a chunk of code that has a global array defined in main as:

static float output[ 2048 ];

When I attempt to print it's contents with either "print output" or even "print output @ 10" st-util crashes with the following messages:

GDB connected.  
libusb_handle_events() timeout  
[!] send_recv  
libusb_submit_transfer(-6)  
[!] send_recv  
Segmentation fault  

I've tried both the 1.0.0 release, and master (f12bde)

Printing normal variables seems to work fine.

I am using a STM32F4-DISCOVERY board, and ChibiOS, my toolchain was created with Gentoo's crossdev.

**Comment by xor-gate** [comment]
Please test again with latest tools in master, keep in mind the gdb-server stubs with the stlink tools are not as complete and tested as the stubs shipped with OpenOCD.

**Comment by dflogeras** [comment]
Wow I forgot about this one, came up with a similar test and confirmed it is still broken on 1.0.0 and 1.1.0, then tried current master d25244304547517f8b67e78a1fb52eaec165b18d and the issue goes away.  Thank you very much!

**Comment by xor-gate** [comment]
Great!, thanks for verifying.

**Comment by xor-gate** [comment]
FYI, I have bumped v1.2.0. Have fun!

**Comment by dflogeras** [comment]
TYVM, was hoping for a new numbered release, now I'll see if I can make a Gentoo ebuild and get it in the official tree.
