### ISSUE TITLE
Interrupts are disabled when debugging on chip using st-util: STM32F071 V6T6

### ISSUE THREAD

**Issue by zyura** [stlink-org/stlink#266]
Firmware works fine when uploaded to target using st-flash but when uploading and debugging the same code using st-util as gdb server all interrupts become disabled.

st-util output:

2014-09-24T23:39:15 INFO src/stlink-common.c: Loading device parameters....
2014-09-24T23:39:15 INFO src/stlink-common.c: Device connected is: F07x device, id 0x20016448
2014-09-24T23:39:15 INFO src/stlink-common.c: SRAM size: 0x4000 bytes (16 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 2048 bytes
2014-09-24T23:39:15 INFO gdbserver/gdb-server.c: Chip ID is 00000448, Core ID is  0bb11477.
2014-09-24T23:39:15 INFO gdbserver/gdb-server.c: Target voltage is 2877 mV.
2014-09-24T23:39:15 INFO gdbserver/gdb-server.c: Listening at *:4242...
2014-09-24T23:39:24 ERROR gdbserver/gdb-server.c: [FP_CTRL] = 0x00000041 expecting 0x00000261
2014-09-24T23:39:24 INFO gdbserver/gdb-server.c: GDB connected.

I'm using STM32F4DISCOVERY board's st-link (target voltage is not connected to the st-link MCU by default).

Maybe this chip is not supported yet (FP_CTRL mismatch)?

Is there any quick workaround?

**Comment by xor-gate** [comment]
The gdb-server stubs in `st-uti`l are currently very minimal and semi-hardcoded currently compared to OpenOCD. For full gdb-server stubs you should use OpenOCD (for now). Sorry!

**Comment by fishpepper** [comment]
I think i am running into the same issue with an stm32f072. When i flash the device with st-flash all interrupts seem to be disabled. When i remove the st link and reset my board everything works.

**Comment by fishpepper** [comment]
this fixed it for me (it seems like my cheap st link clone has no proper reset connection?!)
`diff --git a/src/common.c b/src/common.c
index 74fa104..c053c36 100644
--- a/src/common.c
+++ b/src/common.c
@@ -629,6 +629,7 @@ int stlink_load_device_params(stlink_t *sl) {
 
 int stlink_reset(stlink_t *sl) {
     DLOG("*** stlink_reset ***\n");
+    stlink_write_debug32(sl, 0xE000ED0C, (0x5FA << 16) | (1 << 2));
     return sl->backend->reset(sl);
 }
`
i got it from this issue: https://github.com/texane/stlink/issues/220

**Comment by Nightwalker-87** [comment]
Mentioned fix not included in latest Release v1.6.0. Requires a review to see if this issue has really been solved in the meanwhile.

**Comment by Nightwalker-87** [comment]
@zyura @fishpepper: I'm currently reviewing old issues. Can you please test this with Release v1.2.0? If it does not solve this issue please try later releases, so that this issue can be solved and allocated correctly within the project.

**Comment by Nightwalker-87** [comment]
Does the proposed fix by @fishpepper resolve this issue in general?

**Comment by Nightwalker-87** [comment]
Closed by #341.
