### ISSUE TITLE
`run` gdb command doesn't work

### ISSUE THREAD

**Issue by l29ah** [stlink-org/stlink#267]
(gdb) target extended-remote localhost:4242
Remote debugging using localhost:4242
0x08001154 in ?? ()
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) run

Starting program: /home/l29ah/projects/coreboot/stm32f4-flashrom/serprog-stm32f4discovery/serprog-stm32f4discovery.elf serprog-stm32f4discovery.elf
Remote target does not support "set args" or run <ARGS>
(gdb) c
The program is not being run.

-- GNU gdb (Linaro GDB) 7.5-2012.12-1

**Comment by Nightwalker-87** [comment]
Documentation should be reviewed to verify.

**Comment by Nightwalker-87** [comment]
@prattmic: Are you sure about this? I mean why would it have been added to the README then?

**Comment by Nightwalker-87** [comment]
@xor-gate: The related reference in our README has moved to the tutorial in the meanwhile.
I am not so sure if documentation is wrong here... Can you remember anything from earlier times and/or look into this?

**Comment by Nightwalker-87** [comment]
The `run` command is indeed still present in the unrevised part of our project tutorial.
Could someone rewrite and verify the gdb-related sections? (some hardware would be preferable to do some testing)
