### ISSUE TITLE
[feature] Read protect bits

### ISSUE THREAD

**Issue by AntonLytkinIwdel** [stlink-org/stlink#346]
Do you plan to make this functional?

**Comment by texane** [comment]
no plan yet, but any contribution welcome !

2015-11-08 7:20 GMT+01:00 Anton Lytkin <notifications@github.com>:

**Comment by aric1987** [comment]
https://github.com/aric1987/stlink/
test ok! for  stm32f103c8t6

**Comment by ceremcem** [comment]
@aric1987 Why don't you create a PR for this?

**Comment by Nightwalker-87** [comment]
@ceremcem:  @aric1987 seem to be inactive by now.
I don't know yet, if his patch is still compatible with the current codebase. One needs to check.

**Comment by Nightwalker-87** [comment]
@Ant-ON: As I believe to read from the code that these protect bits are also included in the option bytes, as the whole area is written at once. Is this correct?

**Comment by Ant-ON** [comment]
@Nightwalker-87 Yes, on F0/F1/F3:
```c
  /* Retrieve current values */
  ret = stlink_read_debug32(sl, FLASH_OBR, &optiondata);
  if (ret) {
    return ret;
  }
  ret = stlink_read_debug32(sl, FLASH_WRPR, &protection);
  if (ret) {
    return ret;
  }
```
