### ISSUE TITLE
CLI tools need better argument parsing

### ISSUE THREAD

**Issue by smithbone** [stlink-org/stlink#378]
The v1/v2 checking code for st-flash is dependent on the number of arguments provided.  <size> is listed as an option argument but if you you provide that argument then the argument parser assumes you are talking to a v1 device because 4 arguments are provided.

**Comment by gerryqd** [comment]
Just checked the code, seems the <size> info is useless when it is in "write" mode.

Anyway, this is a bug.

**Comment by xor-gate** [comment]
Did you fixed this issue with pull request #413 ? I did review it and seems to be fine. I'm currently not very happy how the option parsing is implemented and it needs some love and reworking. Thanks for looking into it.

**Comment by gerryqd** [comment]
Sorry, I did not fix it in #413. Personally, I think the opt parse function should be rewritten. Some cases should be taken into account.

**Comment by xor-gate** [comment]
Yeah you are right, I will rename this issue because it is major. I take two small option parsing libraries into account which are both MIT license:

* https://github.com/clibs/flag
* or https://github.com/clibs/commander

**Comment by xor-gate** [comment]
Related to #208

**Comment by Nightwalker-87** [comment]
@gerryqd: What is the current state of this?

**Comment by Nightwalker-87** [comment]
@gerryqd: What is the current state of this?

**Comment by Nightwalker-87** [comment]
@grevaillot: Can you confirm if this resolves with your recent PR?

**Comment by grevaillot** [comment]
i'm a bit puzzled by that piece of code, the v1/v2 stlink handling is a bit broken, the device path is not actually used, and i think it's useless now.

still it would be nice to replace the whole custom opt parsing by something more nice / standard..
