### ISSUE TITLE
JTAG speed/frequency

### ISSUE THREAD

**Issue by jkhax0r** [stlink-org/stlink#462]
In the official ST-LINK utility there is a method to adjust the JTAG/SWD frequency from 4Mhz and down.  Is there an equivalent in this utility?

**Comment by xor-gate** [comment]
This is currently not implemented. And is only available in OpenOCD.

**Comment by jkhax0r** [comment]
I just made a pull request for this... https://github.com/texane/stlink/pull/534

**Comment by xor-gate** [comment]
Thanks @jkhax0r !
