### ISSUE TITLE
Unable to build on ubuntu

### ISSUE THREAD

**Issue by protodmorgan** [stlink-org/stlink#698]
I'm attempting to install this on ubuntu. However, it seem I am missing something.  when I follow the instructions make release. I am hitting the following error:

[RELEASE]
make[1]: *** No targets specified and no makefile found.  Stop.
Makefile:27: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by xor-gate** [comment]
You should run `make clean` because CMake didn't generated any makefiles. Make sure you have installed `cmake libusb-dev` or else it wont build.

**Comment by protodmorgan** [comment]
results in the same issue. 


 sudo apt-get install cmake libusb-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libusb-dev is already the newest version (2:0.1.12-28).
cmake is already the newest version (3.5.1-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 108 not upgraded.


@DESKTOP-SLOJ0HQ:~/stlink$ make
[RELEASE]
make[1]: *** No targets specified and no makefile found.  Stop.
Makefile:27: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by slyshykO** [comment]
You should install libusb-1.0-dev( not sure that is correct name) but pack
may contain libusb-1.0


ср, 28 мар. 2018 г., 19:48 protodmorgan <notifications@github.com>:

**Comment by protodmorgan** [comment]
> You should install libusb-1.0-dev( not sure that is correct name) but pack
>may contain libusb-1.0

even with that installed Same issue

**Comment by slyshykO** [comment]
Ok, I realize that makefile or instruction is outdated. Or both. You can
build with Cmake, or wait for someone fix makefile.

ср, 28 мар. 2018 г., 20:05 protodmorgan <notifications@github.com>:

**Comment by xor-gate** [comment]
You need to make sure the `build` folder is removed when the cmake run failed which `make clean` does.

**Comment by slyshykO** [comment]
I successfully build the stlink following instruction.
And also in Orange Pi Zero, that relies on #621 .

**Comment by protodmorgan** [comment]
thanks..as I said I was probably missing something. trying to learn.

**Comment by protodmorgan** [comment]
Seem to run into a problem now after compiling, I am running st-info etc, and I get. st-info: error while loading shared libraries: libstlink.so.1: cannot open shared object file: No such file or directory 

can confirm those libs exist but are in lib/lib, and I did run ldconfig

**Comment by Vascom** [comment]
It is bug #700

**Comment by fedorg** [comment]
run ldconfig

**Comment by jjmilburn** [comment]
Running `ldconfig` did not resolve this for me. I had to first manually copy the files `libstlink.so.1` / `libstlink.so` to `/usr/bin/lib`.

**Comment by Nightwalker-87** [comment]
Please verify if the problem still exists in Release v1.6.0.

**Comment by Basilisvirus** [comment]
Happened to me when i downloaded Source code (tar.gz).

Then, i downloaded  Source code (zip) and it worked.

**Comment by Nightwalker-87** [comment]
@Basilisvirus: Interesting. Nevertheless both archive files .zip and .tar.gz. are generated automatically by github. Are there any local problems with unzipping .tar.gz or directory paths?

**Comment by Basilisvirus** [comment]
@Nightwalker-87 Thats what i am thinking. Maybe my download was not completed/corrupted or there was an unzip error.

**Comment by Nightwalker-87** [comment]
Could you retry the .tar.gz archive to verify, so that we can finally resolve this issue with the knowledge that both work correctly? That would be great.

**Comment by Basilisvirus** [comment]
I would, but right now i get issue #478 error so let me fix that first xD

**Comment by Nightwalker-87** [comment]
ok, of course we welcome any helpful contribution. :+1:

**Comment by Basilisvirus** [comment]
I re-installed the release 1.6.0, using the **Source code (tar.gz)** and it installed correctly, so there is no issue here.
Plus, i installed it using `sudo make` instead of `make` and all my other installation-based problems were solved as well.

**Comment by Nightwalker-87** [comment]
Yes we can! :+1: :1st_place_medal:

**Comment by Nightwalker-87** [comment]
@protodmorgan: Which version did you originally use? Does it already work with v1.5.1? This would be good to know to allocate this ticket to the correct version in the changelog. I am trying to find the related fix for it.

**Comment by Nightwalker-87** [comment]
> Running `ldconfig` did not resolve this for me. I had to first manually copy the files `libstlink.so.1` / `libstlink.so` to `/usr/local/lib/`. Only then did `ldconfig` make any difference.

@slyshykO: Was this fixed in PR 701? Could you have a look at this?

**Comment by slyshykO** [comment]
@Nightwalker-87  #701 not about this issue.

**Comment by Nightwalker-87** [comment]
Then I don't know either. Does anyone else have an idea on this?
The rest of the issue seems to have resolved from fixing local issues.

**Comment by Nightwalker-87** [comment]
I'd need someone with an ubuntu system for assistance with testing for a final verification with older releases. If this was a general issue on Ubuntu, then I believe this has been fixed in the meanwhile - otherwise it would have derived from a local circumstance we can not reproduce.

**Comment by Nightwalker-87** [comment]
Final review of this issue:
1) `make[1]: *** No targets specified and no makefile found. Stop.`
--> Solution: https://github.com/stlink-org/stlink/issues/698#issuecomment-377037857
2) `st-info: error while loading shared libraries: libstlink.so.1: cannot open shared object file: No such file or directory`
--> Solution: https://github.com/stlink-org/stlink/issues/698#issuecomment-598891035

As there are no remaining open points to address, this issue is now finally closed.
