### ISSUE TITLE
[feature] support STLink/v2 programmer firmware updates (via DFU)

### ISSUE THREAD

**Issue by nerilex** [stlink-org/stlink#720]
I wrote a [tool to update the firmware of an STLink/v2 programmer][1] itself via DFU on base.

If there is interest I would bring the code into a state ready for a pull-request, if not I would change the code in other ways to make it a separate tool.

Currently my code still contains GPL-code (of myself) and lots of dirty hacks and debug stuff, which will be removed soon.

The update tool was tested with cheap STLink/v2-clones.

Best regards,
~  bg

[1]: https://c0de.pw/bg/stlink/tree/fw-update

**Comment by xor-gate** [comment]
It would be nice to have it in texane/stlink, but it must be relicensed to the 3 Clause BSD to be merged. It is unacceptable for the project to mix GPL and permissive licenses.

**Comment by nerilex** [comment]
relicensing won't be a problem. The GPL-stuff is only in an AES-implementation I copied from one of my other projects.

For now I have put the functionality into a separate tool called /st-fwupdate/.

**Comment by xor-gate** [comment]
Feel free to wrap up and send a PR on github for the project so we can have a look for integration. Please also add some documentation under the doc/* folder, as markdown file and manpage. Thanks for you effort!

**Comment by nerilex** [comment]
Could you create a feature branch for me, to work on the integration?

Since I somehow need feedback how to integrate the stuff, which extends the backend, matching the philosophy of the current devs :-)

**Comment by xor-gate** [comment]
@nerilex sorry for the late reply I was fearly busy past weeks. You should fork the project, create a branch (e.g feature/issue-720) and add create a `[WIP]` in the title pull request for texane/stlink project. If something is not clear, feel free to ask. Thanks!

**Comment by Nightwalker-87** [comment]
@nerilex: Sry for the delay. I just came across this issue during a review... Is your offer still open? :laughing: It certainly would be a "nice to have". Please let us know.

**Comment by Nightwalker-87** [comment]
ping @nerilex

**Comment by Nightwalker-87** [comment]
Closed due to inactivity and missing interest.
