### ISSUE TITLE
[install] Windows binary is configured to a hard-coded path

### ISSUE THREAD

**Issue by gworkman** [stlink-org/stlink#738]
When using the latest (1.3.0) windows binary release, the path seems to be hard-coded. When running st-util.exe in cmd, the output is "C:\Users\Jerry\Desktop\st-util.exe not found". The file is located at C:\stlink\st-util.exe instead.

**Comment by Nightwalker-87** [comment]
This will likely resolve with our upcoming enhanced cpack packaging.

**Comment by Nightwalker-87** [comment]
Windows binary packages distributed as of Release v1.6.1 will not contain any hardcoded paths.
