### ISSUE TITLE
Cause st-util to quit

### ISSUE THREAD

**Issue by donmr** [stlink-org/stlink#739]
- [X] Operating system: e.g Linux, Mac OS X, Windows (with specific version)
- [X] Stlink tools version and/or git commit hash: v 1.5.1
- [X] Stlink commandline tool name: `st-util`

When st-util is opened in extended mode it seems to set st-persistent to 1.
Is there any way to undo this, or otherwise cause st-util to terminate, after the link is closed?

I am trying to automate testing and want each gdb run to have it's own st-util instance so that the semihosting accesses are to the right directory.  It's easy to start st-util but it won't stop.

I don't like running ps and kill as there could be other things going on.

If there is not a way, is it OK for me to add a persist 0/1 remote command?  Or does anyone want to suggest another way to get this function?

Don

**Comment by donmr** [comment]
Missing OS info: Linux Mint 18.3 (Ubuntu 16.04)

Do I just need to not use extended-remote mode?

**Comment by xor-gate** [comment]
Hi @donmr sorry for the late reply, luckily you have found a solution!
