### ISSUE TITLE
[feature] Flashing hex with CCM section on STM32F4

### ISSUE THREAD

**Issue by vidavidorra** [stlink-org/stlink#740]
- [x] Programmer/board type:
    STLINK/V2
- [x] Programmer firmware version:
- [x] Operating system
  macOS Mojave
- [x] Stlink tools version and/or git commit hash:
   stlink 1.5.1
- [x] Stlink commandline tool name:
    `st-flash`
- [x] Target chip (and optional board):
    STM32F405RG

I have a device where I use the [CCM section of the device](https://www.st.com/resource/en/datasheet/stm32f405rg.pdf#page=71) (separate part of RAM) which I defined in the linker and compiles/links successfully. When I want to the hex file however, I get an error that the address is too high for the device. It's at a different address than the RAM so maybe st-flash calculates the write size in bytes based on the lowest and highest address or something.
- SRAM `0x20000000` - `0x20020000` (128 KiB)
- CCM `0x10000000` - `0x10010000` (64 KiB)

Output:

```shell
$ st-flash --reset --format ihex write ./cmake-build-release/example-app.hex
st-flash 1.5.1
2018-10-01T16:10:34 INFO common.c: Loading device parameters....
2018-10-01T16:10:34 INFO common.c: Device connected is: F4 device, id 0x10076413
2018-10-01T16:10:34 INFO common.c: SRAM size: 0x30000 bytes (192 KiB), Flash: 0x100000 bytes (1024 KiB) in pages of 16384 bytes
2018-10-01T16:10:35 INFO common.c: Attempting to write 134087680 (0x7fe0400) bytes to stm32 address: 134348800 (0x8020000)
2018-10-01T16:10:35 ERROR common.c: addr too high
stlink_fwrite_flash() == -1
```

Expected/description:
I'd expect it to flash, but am not 100% sure whether I did something wrong in compiling/linking or this is a bug in st-flash.

**Comment by vidavidorra** [comment]
Ok, did some more testing today and found that when I have my linker as the example below, my hex file, or the st-link tries to flash a bigger flash than I actually have. When I change `.myBufBlock :` to `.myBufBlock (NOLOAD):` it does flash and I can use the CCM (only tested with 1 KiB buffer for now).
I haven't compared the hex files of the variants to see whether the hex without `NOLOAD` is bigger than the other one. If the latter is the case that would explain what is happening as the hex file might start at the address of the CCM, which would roughly double the size that I'm flashing.

```assembly
SECTIONS
{
  /* placing my named section at given address: */
  .myBufBlock :
  {
    . = ALIGN(4);
    KEEP(*(.myBufSection)) /* keep my variable even if not referenced */
  } > CCM
}

Using the `NOLOAD` the section is of course not initialised with a value, but I'm not sure whether that would be possible with CCM, or with RAM for that matter. Would like to know if someone has more experience with this and knows what is possible.

I'll do some more testing and report back here.

**Comment by xor-gate** [comment]
Hi @vidavidorra sorry for the late reply. I was unaware of the CCM section. I think currently the texane/stlink tooling program loaders don't support writing to this area. Even if the windows tool doesn't support this it would be a nice addition.

**Comment by Nightwalker-87** [comment]
Closed due to inactivity and missing interest.
