### ISSUE TITLE
[doc] Library usage

### ISSUE THREAD

**Issue by BigfootN** [stlink-org/stlink#800]
Hello,

I would like to know where I can find (apart from reading the headers), if possible, any documentation on how to use the `stlink` library ?

Thank you very much in advance.

**Comment by xor-gate** [comment]
Thats a good question there is a very very minimal example here https://github.com/texane/stlink/tree/6db0fc243ffb90aed314ef1d59811486e9214883/doc/app-example. The library is not (very well) documented, the library is used for lowlevel access on the stlink programmer and is not often used outside the project.

**Comment by Nightwalker-87** [comment]
@BigfootN: Did this help you any further? I agree that we need more documentation on this.

**Comment by Nightwalker-87** [comment]
@Ant-ON You recently mentioned that you use the library itself. What would you document on how to use it from your personal experience?

**Comment by Nightwalker-87** [comment]
Closed due to inactivity and missing interest.
