### ISSUE TITLE
[feature] Add support for Serial Wire Output (SWO) viewer (ITM instrumentation trace)

### ISSUE THREAD

**Issue by chopin1998** [stlink-org/stlink#815]

**Comment by xor-gate** [comment]
Currently the texane/stlink project doesn't support SWO. But it could be implemented of course.

**Comment by xor-gate** [comment]
You could use OpenOCD for that with the following settings:

```
itm port 0 on
tpiu config internal <logfile> uart off <cpu_freq_herz>
```

For some other readers: https://mcuoneclipse.com/2016/10/17/tutorial-using-single-wire-output-swo-with-arm-cortex-m-and-eclipse/

**Comment by chopin1998** [comment]
> You could use OpenOCD for that with the following settings:
> 
> ```
> itm port 0 on
> tpiu config internal <logfile> uart off <cpu_freq_herz>
> ```
> 
> For some other readers: https://mcuoneclipse.com/2016/10/17/tutorial-using-single-wire-output-swo-with-arm-cortex-m-and-eclipse/

thank you very much!
