### ISSUE TITLE
[distribution] 'make package' for debian based distros

### ISSUE THREAD

**Issue by zx81a** [stlink-org/stlink#845]
Hello.

Debian package created with 'make package' does not contain **postinst** script.
I do not know how to add it, but installation should run  **depmod** after sucess.

**Comment by Nightwalker-87** [comment]
@slyshykO: Would it make sense to fix this as well, as we‘re looking at compiling and build issues at the moment?

**Comment by slyshykO** [comment]
@Nightwalker-87 I know nothing about packaging, sorry.
We should attract people who know.
Try to search in discussion #701

**Comment by Nightwalker-87** [comment]
Ok, no problem. Haven‘t reviewed that PR yet, but thx for the hint.

**Comment by Nightwalker-87** [comment]
@Vascom or @bluca maybe?

**Comment by Vascom** [comment]
I am only for Fedora.

**Comment by bluca** [comment]
It looks like the makefiles are using CMake's embedded package generator. I am not familiar with it, and have no time to look into it - sorry.

**Comment by Nightwalker-87** [comment]
Related to #877.
