### ISSUE TITLE
how to use stlink to debug iap program

### ISSUE THREAD

**Issue by mttbx** [stlink-org/stlink#873]
I want to debug iap program by stlink, however I don't know how to burn two program at different flash address through st-util / gdb.

**Comment by Nightwalker-87** [comment]
Please describe your issue more precisely and specify the system you use to facilitate individual support.

**Comment by mttbx** [comment]
I'm using stm32 chip to run c programs in Linux. I use gdb to connect remote st-util server so I can debug my program. My program has two parts. The first part is boot sub program, and the second is app sub program. In the boot program, it will do some work and then jump to the second program. The two programs can be compiled seperatly, and they both contains the main function. I can boot these two program into the flash of chip through gdb using load command (remote connect to st-util server). Here's the question, tt seems there's two sets of symbols, and how can I guide gdb to help me debug them.&nbsp;

梅骁同济大学测绘与地理信息学院


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nightwalker-87"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 晚上10:05
收件人: "texane/stlink"<stlink@noreply.github.com&gt;; 
抄送: "echo"<408425540@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [texane/stlink] how to use stlink to debug iap program (#873)




Please describe your issue more precisely and specify the system you use to facilitate individual support.

**Comment by mttbx** [comment]
I'm using stm32 chip to run c programs in Linux. I use gdb to connect remote st-util server so I can debug my program. My program has two parts. The first part is boot sub program, and the second is app sub program. In the boot program, it will do some work and then jump to the second program. The two programs can be compiled seperatly, and they both contains the main function. I can boot these two program into the flash of chip through gdb using load command (remote connect to st-util server). Here's the question, tt seems there's two sets of symbols, and how can I guide gdb to help me debug them.

**Comment by Nightwalker-87** [comment]
This is actually a question related to the GNU Debugger (gdb) which is not part of this `stlink` toolset itself.
I'd suggest you to consult the IRC-Support channel of the gdb project with this.
It can be found here: https://www.gnu.org/software/gdb/irc/

As this question is not related to the `stlink` project and adequate advice has been given, this issue will now be closed.
