### ISSUE TITLE
st-flash: incorrect file name handling

### ISSUE THREAD

**Issue by tdjastrzebski** [stlink-org/stlink#879]
In case of incorrect bin file name **st-flash** fails with error:
`ERROR common.c: map_file() == -1`
I suggest more descriptive message.

**Comment by Nightwalker-87** [comment]
So what would you suggest instead?

**Comment by tdjastrzebski** [comment]
I suggest message:
`Unable to open [file-name] file.`

**Comment by Nightwalker-87** [comment]
Ok, are you with Release v1.6.0 ?

**Comment by tdjastrzebski** [comment]
So far so good :)
It seems to work better than 1.5.1 although I have not tested it extensively yet.

**Comment by Nightwalker-87** [comment]
@tdjastrzebski: Can you submit a PR?

**Comment by Nightwalker-87** [comment]
Duplicate of #650.
