### ISSUE TITLE
[feature] Adjust the JTAG/SWD frequency via cmdline option

### ISSUE THREAD

**Issue by Nightwalker-87** [stlink-org/stlink#893]
As far as I can see, we are lacking a HowTo for the feature above, added by @jkhax0r in #534 
Who can contribute and help with this?

**Comment by Nightwalker-87** [comment]
Taking a closer look at this reveals that the related functionality is only hardcoded without the ability to pass the JTAG/SWD frequency as an option parameter to `st-util`, what I actually expected to find. Thus there is also no documentation that can be added until this feature becomes usable from the command line. In the current state seems useless to me. Against this background we yet have another topic to be dealt with... Volunteers?

**Comment by chenguokai** [comment]
I am working on it.
