### ISSUE TITLE
[MacBook]: [make release issue]

### ISSUE THREAD

**Issue by lonsathing** [stlink-org/stlink#957]
[RELEASE]
[ 22%] Built target stlink-static
[ 27%] Built target st-info
[ 38%] Built target st-util
[ 47%] Built target st-flash
[ 69%] Built target stlink
[ 72%] Linking C executable ../../bin/stlink-gui
ld: framework not found -lCocoa
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/stlink-gui] Error 1
make[2]: *** [src/stlink-gui/CMakeFiles/stlink-gui.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release] Error 2

when I was building the stlink on my computer .and I also check my Xcode have the famework named cocoa.the "lcocoa" I can't research in google

**Comment by Nightwalker-87** [comment]
Invalid ticket. Please refer to pinned README and our guidelines and reopen in a valid format. Thank you for your understanding.
