### ISSUE TITLE
Release's artefacts for v1.6.1 marked as v1.6.0.

### ISSUE THREAD

**Issue by slyshykO** [stlink-org/stlink#975]
Need to fix versioning of artefacts attached to release.

**Comment by Nightwalker-87** [comment]
Correct

**Comment by Nightwalker-87** [comment]
Will be fixed soon - it should only be related to the name. Thx for reporting.

**Comment by Nightwalker-87** [comment]
With new packages built from the `master` branch, the version in the package name is correct now.
