### ISSUE TITLE
Isn't $(prefix)/include/stm32.h too generic?

### ISSUE THREAD

**Issue by blacklion** [stlink-org/stlink#976]
I'm not sure, is it bug or "as intended" but previous versions of stlink (1.6.0 and earlier) installed main `include/stlink.h` and several other headers under `include/stlink/`.
1.6.1 installs `include/stlink.h`, `include/stm32.h` and several other headers under `include/stlink/`.
Is it as intended? `stm32.h` looks too generic to be installed into system-wide include directory, isn't it?

**Comment by Nightwalker-87** [comment]
These project paths are still subject to change because of ongoing work. We had to find an interim solution for recent Release v1.6.1, because we could not restructure the project all at once. Please give us some time to address this within already existing tickets.
