### ISSUE TITLE
Fails to connect and program STM32F103C8 boards (bluepill)

### ISSUE THREAD

**Issue by oloftangrot** [stlink-org/stlink#984]
Hi there. 
I have used an older build 1.3.1-15-g3d24377 some time with stable operation.

But then I built a new version of the stlink tools with the latest from github and using the same ST-LINK v2 interface and STM32-devices nothing works

 ./st-info --version 
v1.6.0-378-gd473c99

st-info --chipid
returns 0x0000

After an firmware upgrade of the programmer interface using ST-LINK utility (from st) the older  1.3.1-15-g3d24377 build still manages returns correct chip id and program devices but has intermittent operation fails a lot after the upgrade.
 
If it is useful I could try to connect a logic analyzer and capture traffic from the 1.3.1-15 version when it reads successfully and fails.

Regards

Olof

**Comment by Nightwalker-87** [comment]
I can verify that the STM32F103C8 Bluepill board works successfully with v1.6.0, as I did some testing with this hardware myself. `st-info` also returns the correct chip-id here.

As this ticket has not been opened correctly according to the project's contribution guidelines, it will now be closed.
